name: spacious_widgets
description: A library to insert SizedBox for space between every child in Column, Row, or any List<Widget>
version: 1.1.0+1
homepage: https://github.com/alraj-dev/spacious_widgets

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: