name: spacious_widgets
description: Inserts SizedBox between children widgets
version: 1.0.0
homepage: https://github.com/alraj-dev/spacious_widgets

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: